package com.sample
 
import com.sample.Message;
import java.util.ArrayList;
import function com.sample.UserInterface.*;
 
rule "Init"
	when
		ui : UserInterface()
	then
		System.out.println("Witam w grach komputerowych");
		
		ArrayList<String> answers = new ArrayList<>();
		answers.add(Constants.PAST);
		
		ui.setAnswers(answers, Constants.TITLE_0);
end
/*
rule "messageStatusChanged"
	when
		m : Message( status == Message.CHANGED )
	then
		System.out.println("message : " + m.getMessage());
		m.setStatus(Message.ADRESSED);
		update(m);
*/
rule "PAST"
	when 
		ui : UserInterface()
		m : Message(message == Constants.PAST)
	then
		ArrayList<String> answers = new ArrayList<>();
		answers.add(Constants.TITLE_01);
		answers.add(Constants.TITLE_10);
		ui.setAnswers(answers, Constants.TITLE_1);
end

rule "recent past"
	when
		ui : UserInterface()
		m : Message(message == Constants.TITLE_01)
	then 
		ArrayList<String> answers = new ArrayList<>();
		answers.add(Constants.YES);
		answers.add(Constants.NO);
		ui.setAnswers(answers, Constants.TITLE_2);
end

rule "not like cold war"
	when
		ui : UserInterface()
		m1 : Message(message == Constants.TITLE_01)
		m2 : Message(message == Constants.NO)
	then 
		ArrayList<String> answers = new ArrayList<>();
		answers.add(Constants.YES);
		answers.add(Constants.NO);
		ui.setAnswers(answers, Constants.TITLE_3);
end

rule "not like wild west"
	when
		ui : UserInterface()
		m1 : Message(message == Constants.TITLE_01)
		m2 : Message(message == Constants.NO)
		m3 : Message(message == Constants.NO)
	then 
		ArrayList<String> answers = new ArrayList<>();
		answers.add(Constants.YES);
		answers.add(Constants.NO);
		ui.setAnswers(answers, Constants.TITLE_4);
end



