package com.sample
 
import com.sample.Message;
import java.util.ArrayList;
import function com.sample.UserInterface.GetQuestions;
 

rule "Init"
	when
	then
		System.out.println("Witam w grach komputerowych");
		ArrayList<String> ans = new ArrayList<>();
		ans.add("PAST");
		ans.add("Present");
		Message mes = GetQuestions(ans, "LET'S PLAY A GAME\n\nfirst: what time period are you thinking?");
		System.out.println("Halo, tutaj " + mes.result);
		insert(mes);
end

rule "PAST"
	when 
		Message(result == "PAST")
	then
		System.out.println("yee");
end

rule "PRESENT"
	when 
		Message(result == "Present")
	then
		System.out.println("What???");
end
